bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: gM8XItZ78vLTHpG2Ss5+9XqOitTJjS/XGF3osLdzn5r9LcLOiaJ0kgRMZElA8myFqjc1hJztE9cqskY59LCPFpaybxjQGit8QwOAL4kphvIKptdmL0oSQBiu+F87feQgiEjMPOV09eh2fYdk4yOBt/QiqGfY5aEgWGq9teRpYarSjs6QYRy0Rclr7ni3wkwZ1wQ9M3MFgYEigfrNmiexgseUr2xW/cHRmqxVa74RT0ehPqE4eFQfrdimC/cgSerHY6uGjDIGDmGfRyP9T3jbzTiXFUpAl+nOQH8jjvXdufJDddkDt+JXSvZrFFUiRR5K5OLJw6qnHadOIS0HM3Wmbz4qKyXMS4H21YVVbXByvbUaiFf65xjnNmF9zB1wM4aU6VMoMnhQLIKno5U9RE45TLhoEKJL6I44ZoWPROkXgU7+GoElQdoMS2sm5Iu3aHbEUP90Ecxv0ouBkg4eB3SuZSlQqXxs9MXkmp82dPTlvqV+Tli9HtyUnX++BeIh46evCySUSVQW6WRCn05G+xLVyc3VEeNJO6rLO+/bc1mwb4ULq2fB41YfL1Gb+S57MCxOk214dwS7aFC+bqTNgzaE2b0McQCDHNLqpcuCFyNn2i/x0r/Ik5q01FdF1X692O6t/8SublKFkohpJJAO9tTsore4ON3iV2/ua0C/l/1UsSQ=
conda_forge_output_validation: true
